<h1>Numpy</h1>

_NumPy is a Python library._<br>
_NumPy is used for working with arrays._<br>
_NumPy is short for "Numerical Python"._<br><br>

In [1]:
import numpy as np

In [2]:
n_list = [1,2,3,4]
arr = np.array(n_list) # convert into a array
print("Arrray type: ", type(arr), "\nArray: ", arr)

Arrray type:  <class 'numpy.ndarray'> 
Array:  [1 2 3 4]


In [3]:
# getting the shape of array

arr.shape # col, row

(4,)

In [4]:
# lets create a 2d array of (4, 3)

arr1 = [1,2,3,4]
arr2 = [5,6,7,8]
arr3 = [9,10,11,12]

arr_2d = np.array([arr1, arr2, arr3])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# now lets reshape it he 2d array into (3, 4)

arr_2d.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Indexing

In [6]:
# Acessing the arr ele
print(arr_2d)
arr_2d[1][0]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


5

In [7]:
arr_2d[0:, 0:2] # row, col

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [8]:
arr_2d[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [9]:
arr_2d[1, 1:]

array([6, 7, 8])

In [12]:
arr = np.arange(0, 10, step=2) #create new elements with the steps
arr

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(1, 10, 50) #create new 50 elements in that range

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [16]:
arr2 = arr.copy()
arr2

array([0, 2, 4, 6, 8])

### Some conditions usefull for exploratary Data Analysis

In [18]:
# check which of the elements are less than 2
arr<2

array([ True, False, False, False, False])

In [24]:
#create an array and rearrange it

arr = np.arange(0, 10).reshape(5,2)

In [26]:
arr*arr #multiply

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [31]:
np.ones(5, dtype=int) #create a array of of 1 of 5 elns

array([1, 1, 1, 1, 1])