<h1>Numpy</h1>

_NumPy is a Python library._<br>
_NumPy is used for working with arrays._<br>
_NumPy is short for "Numerical Python"._<br><br>

In [2]:
import numpy as np

In [6]:
n_list = [1,2,3,4]
arr = np.array(n_list) # convert into a array
print("Arrray type: ", type(arr), "\nArray: ", arr)

Arrray type:  <class 'numpy.ndarray'> 
Array:  [1 2 3 4]


In [8]:
# getting the shape of array

arr.shape # col, row

(4,)

In [10]:
# lets create a 2d array of (4, 3)

arr1 = [1,2,3,4]
arr2 = [5,6,7,8]
arr3 = [9,10,11,12]

arr_2d = np.array([arr1, arr2, arr3])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# now lets reshape it he 2d array into (3, 4)

arr_2d.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Indexing

In [22]:
# Acessing the arr ele
print(arr_2d)
arr_2d[1][0]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


5

In [38]:
arr_2d[0:, 0:2] # row, col

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [41]:
arr_2d[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [42]:
arr_2d[1, 1:]

array([6, 7, 8])