<h1> Pandas </h1>

_pandas is an open-source library built on top of numpy providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. It allows for fast analysis and data cleaning and preparation._

In [2]:
import numpy as np
import pandas as pd

In [23]:
# creating a dataset in pandas

df = pd.DataFrame(np.arange(0, 20).reshape(5,4), index=['row1', 'row2', 'row3', 'row4', 'row5'], columns=['column1', 'column2', 'column3', 'column4'])

In [24]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [25]:
# for saving the dataset as csv file

df.to_csv("pd_test.csv")

### DataFrame vs DataSeries

#### DataFrame:
_A DataFrame is a data structure that organizes data into a 2-dimensional table of rows and columns, much like a spreadsheet. DataFrames are one of the most common data structures used in modern data analytics because they are a flexible and intuitive way of storing and working with data._

#### Series:
_Series is the data structure for a single column of a DataFrame, not only conceptually, but literally, i.e. the data in a DataFrame is actually stored in memory as a collection of Series._

In [31]:
# accessing the data
# 1. loc ----> row indexes (dataseries)
# 2 iloc ----> row and col indexes (dataframe)

df.loc['row3']

column1     8
column2     9
column3    10
column4    11
Name: row3, dtype: int32

In [30]:
# check the type of

type(df.loc['row3'])

pandas.core.series.Series

In [33]:
# using iloc

df.iloc[:]

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [44]:
df.iloc[0:2 , 0:3]

column1  column2  column3
row1        0        1        2
row2        4        5        6

In [45]:
type(df.iloc[0:2 , 0:3])

pandas.core.frame.DataFrame

In [50]:
# coverting the dataframe into an array

print(df.iloc[:2, :3].values)
df.iloc[:2, :3].values.shape

[[0 1 2]
 [4 5 6]]


(2, 3)

In [52]:
# checking the mull values of a dataset

print(df.isnull())
df.isnull().sum()

      column1  column2  column3  column4
row1    False    False    False    False
row2    False    False    False    False
row3    False    False    False    False
row4    False    False    False    False
row5    False    False    False    False


column1    0
column2    0
column3    0
column4    0
dtype: int64

In [59]:
# checking the frequency of values of a particular col

df['column2'].value_counts()

1     1
5     1
9     1
13    1
17    1
Name: column2, dtype: int64

In [63]:
# get the unique values of a col

df['column1'].unique()

array([ 0,  4,  8, 12, 16])